project: 
  type: website
  
website: 
  page-navigation: true
  title: "PSYC 641 - Graduate Research Methods" 
  site-url: "https://dharaden.github.io/psyc641-s25" 
  repo-url: https://github.com/dharaden/psyc641-s25 
  repo-actions: [issue]
  
  page-footer:
    right: "This page is built with ☕ and [Quarto](https://quarto.org/)."
    left: "&copy; CC-By Dustin Haraden, 2025"
    
  sidebar:
    logo: "images/example_hex.png"
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://google.com
        text: "Your Website"
      - icon: github
        href: https://github.com/
        text: "Your Github"
      - icon: twitter
        href: https://twitter.com/
        text: "Your Twitter"         

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Home
      - newpage.qmd
      - section: subsection-files/index.qmd
        contents: 
          - subsection-files/sub_1.qmd
          - subsection-files/sub_2.qmd 
      - learning-more.qmd


format:
  html:
    theme:
      light: [cosmo, theme.scss] # from https://github.com/sta210-s22/website/blob/main/_quarto.yml
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true


filters:
  - include-files.lua
  - quarto

  
