project: 
  type: website
  
website: 
  page-navigation: true
  title: "PSYC 641 - Graduate Research Methods" 
  site-url: "https://dharaden.github.io/psyc641-s25" 
  
  repo-url: https://github.com/dharaden/psyc641-s25 
  repo-actions: [edit, issue]

  open-graph: true
  
  page-footer:
    right: "This page is built with ☕ and [Quarto](https://quarto.org/)."
    left: "&copy; CC-By Dustin Haraden, 2025"
    background: "#D9E3E4"
    
  sidebar:
    background: "#D9E3E4"
    logo: "images/641_hex.png"
    pinned: true
    align: center
    tools:
      - icon: chalkboard
        href: https://mycourses.rit.edu/d2l/login
        text: "myCourses"
        

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "Course information"
        contents: 
          - href: index.qmd
            text: Schedule
      - section: "Weekly materials"
        contents:
          - href: weeks/week-10.qmd
            text: "Week 10"
      - section: "Project" 
        contents:
          - href: project/index.qmd
            text: Project Overview
      - section: "Additional info"
        contents:
          - href: learning-more.qmd

format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true

freeze: auto

editor: visual


filters:
  - include-files.lua
  - quarto

  
