project: 
  type: website
  
website: 
  page-navigation: true
  title: "PSYC 640 - Graduate Statistics" 
  site-url: "https://dharaden.github.io/psyc640" 
  
  repo-url: https://github.com/dharaden/psyc640 
  repo-actions: [edit, issue]



  open-graph: true
  
  page-footer:
    right: "This page is built with ☕ and [Quarto](https://quarto.org/)."
    left: "&copy; CC-By Dustin Haraden, 2025"
    background: "#ADE0C0"
    
  sidebar:
    background: "#ADE0C0"
    logo: "images/640_hex.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/dharaden/psyc640
        text: "GitHub"
      - icon: chalkboard
        href: https://mycourses.rit.edu/d2l/login
        text: "myCourses"
        

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "Course information"
        contents: 
          - href: course-overview.qmd
            text: "Overview"
          - href: syllabus.qmd
            text: "Syllabus"
          - href: index.qmd
            text: "Schedule"
      - section: "Weekly Materials"
        contents:
          - href: weeks/week-1.qmd
            text: "Week 1"
      - section: "Labs"
        contents:
          - href: labs/lab-1_data-workflow.qmd
            text: "Lab 1 - Data Intro"
      - href: previous-years.qmd
        text: Previous Years

format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true

freeze: auto

editor: visual


filters:
  - include-files.lua
  - quarto

  
