---
title: Schedule
---

## **AWARE-AI: Dark R's Organization**

<div>

+----+-------+------------------------------------------------+------------------------------------------------------------------------------+------------------------------------------------------------------+
|    | Date  | Topic                                          | Slides                                                                       | Labs                                                             |
+:==:+:=====:+:==============================================:+:============================================================================:+:================================================================:+
| 1  | 08-25 | Getting set up + R foundations                 | [💻Getting Started - Data](../slides/lec-1_background.html){target="_blank"} | [Lab 1 - Intro to Data Workflow](/labs/lab-1_data-workflow.html) |
+----+-------+------------------------------------------------+------------------------------------------------------------------------------+------------------------------------------------------------------+
| 2  | 09-01 | LABOR DAY                                      | LABOR DAY                                                                    | [Lab 2 - Data Wrangling](/labs/lab-2_data-wrangling.html)        |
+----+-------+------------------------------------------------+------------------------------------------------------------------------------+------------------------------------------------------------------+
| 3  | 09-08 | Descriptives, Visualizations + Communication   | [💻 Data Wrangling](../slides/lec-3_wrangle.html){target="_blank"}           |                                                                  |
|    |       |                                                |                                                                              |                                                                  |
|    |       |                                                | [💻 Describe & Visualize](../slides/lec-3_desc-viz.html){target="_blank"}    |                                                                  |
+----+-------+------------------------------------------------+------------------------------------------------------------------------------+------------------------------------------------------------------+
| 4  | 09-15 | Design, Sampling + Inference                   |                                                                              |                                                                  |
+----+-------+------------------------------------------------+------------------------------------------------------------------------------+------------------------------------------------------------------+
| 5  | 09-22 | Correlation + Effect Sizes                     |                                                                              |                                                                  |
+----+-------+------------------------------------------------+------------------------------------------------------------------------------+------------------------------------------------------------------+
| 6  | 09-29 | Comparing Groups                               |                                                                              |                                                                  |
+----+-------+------------------------------------------------+------------------------------------------------------------------------------+------------------------------------------------------------------+
| 7  | 10-06 | Simple Linear Regression                       |                                                                              |                                                                  |
+----+-------+------------------------------------------------+------------------------------------------------------------------------------+------------------------------------------------------------------+
| 8  | 10-13 | FALL BREAK                                     |                                                                              |                                                                  |
+----+-------+------------------------------------------------+------------------------------------------------------------------------------+------------------------------------------------------------------+
| 9  | 10-20 | Variability & Model Fit                        |                                                                              |                                                                  |
+----+-------+------------------------------------------------+------------------------------------------------------------------------------+------------------------------------------------------------------+
| 10 | 10-27 | Multiple Regression I: Adding Predictors       |                                                                              |                                                                  |
+----+-------+------------------------------------------------+------------------------------------------------------------------------------+------------------------------------------------------------------+
| 11 | 11-03 | Multiple Regression II: Categorical Predictors |                                                                              |                                                                  |
+----+-------+------------------------------------------------+------------------------------------------------------------------------------+------------------------------------------------------------------+
| 12 | 11-10 | Assumptions + Model Diagnostics                |                                                                              |                                                                  |
+----+-------+------------------------------------------------+------------------------------------------------------------------------------+------------------------------------------------------------------+
| 13 | 11-17 | Expanding Regression                           |                                                                              |                                                                  |
+----+-------+------------------------------------------------+------------------------------------------------------------------------------+------------------------------------------------------------------+
| 14 | 11-24 | Model Building + Comparison                    |                                                                              |                                                                  |
+----+-------+------------------------------------------------+------------------------------------------------------------------------------+------------------------------------------------------------------+
| 15 | 12-01 | Making R Work for You                          |                                                                              |                                                                  |
+----+-------+------------------------------------------------+------------------------------------------------------------------------------+------------------------------------------------------------------+
| 16 | 12-08 | Wrapping Up + Workshop                         |                                                                              |                                                                  |
+----+-------+------------------------------------------------+------------------------------------------------------------------------------+------------------------------------------------------------------+

</div>

[*Introduction to Modern Statistics (2e)*](https://openintro-ims.netlify.app/){target="_blank"} –\> IMS

[*Learning Statistics with R*](https://learningstatisticswithr.com/book/){target="_blank"} –\> LSR

[*R for Data Science (2e)*](https://r4ds.hadley.nz/){target="_blank"} –\> R4DS

[*Modern Statistics with R (2e)*](https://www.modernstatisticswithr.com/){target="_blank"} –\> MSR

[*Statistical Thinking*](https://statsthinking21.github.io/statsthinking21-core-site/){target="_blank"} –\> ST

[*An Introduction to Statistical Learning (2e)*](https://www.statlearning.com/){target="_blank"} –\> ISL

[*Data Analysis: A Model Comparison Approach to Regression, ANOVA, and Beyond (3rd ed.)*](https://sadbhavnapublications.org/research-enrichment-material/2-Statistical-Books/Data-Analysis-A-Model-Comparison-Approach-To-Regression,-ANOVA,-and-Beyond.pdf){target="_blank"} –\> DA

```{r echo = FALSE}

knitr::knit_exit()
```

|      |      |       | Prepare | Slides | AE  |  Labs  | HW  | Exam | Project |
|------|------|-------|:-------:|:------:|:---:|:------:|:---:|:----:|:-------:|
| Week | Date | Topic |   📖    |   🖥️   | 📋  | [💻]() | ✍️  |  ✅  |   📂    |
